### ISSUE TITLE
Pendulum x position is wrong, bug with the placement of t 

### ISSUE THREAD

**Issue by beckynevin** [deepskies/DeepBench#121]
**Describe the bug**
The pendulum x position always begins at x = 0 for t = 0. It should begin at a different x value (positive or negative) if the starting angle of the pendulum is not 0 degrees. This makes me think there's some bug having to do with parenthesis in the code. I would like to double check the math of the pendulum as we debug this.

**To Reproduce**
1. Go to the example notebook for the pendulum
2. Alter the starting angle
3. Re-create the plot at the bottom
4. Observe that the starting position (at t = 0) is always x = 0 regardless of the starting angle.

**Expected behavior**

**Screenshots**
<img width="524" alt="image" src="https://github.com/deepskies/DeepBench/assets/26393168/8c96ede0-daf1-44e0-a92c-858f65ed15b9">

**Comment by voetberg** [comment]
@beckynevin was this solved in release 2.2.0?

**Comment by beckynevin** [comment]
This was solved, I'm closing the issue.
